  frontend:
    build:
      context: ./frontend # Adjust to your frontend's Dockerfile path
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend # Adjust to your backend's Dockerfile path
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://*:5000
      - ConnectionStrings__DefaultConnection=Server=db;Database=TechDictionaryDB;User ID=sa;Password=YourStrong@Passw0rd;MultipleActiveResultSets=True;TrustServerCertificate=True
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
